// index.js

// 1. IMPORT REQUIRED LIBRARIES
// ===================================
const { Client, GatewayIntentBits, EmbedBuilder } = require('discord.js');
require('dotenv').config();


// 2. CLIENT SETUP
// ===================================
// (This section remains unchanged)
const client = new Client({
    intents: [
        GatewayIntentBits.Guilds,
        GatewayIntentBits.GuildMessages,
        GatewayIntentBits.MessageContent
    ]
});
const targetChannelId = process.env.TARGET_CHANNEL_ID;


// 3. EVENT LISTENERS
// ===================================

// 'ready' event: (This section remains unchanged)
client.once('ready', () => {
    console.log(`✅ Bot is online! Logged in as ${client.user.tag}`);
    console.log(`👀 Watching channel: ${targetChannelId}`);
});

// 'messageCreate' event: Updated to put links in a code block.
client.on('messageCreate', (message) => {
    if (message.author.bot) return;

    if (message.channel.id === targetChannelId) {
        if (message.attachments.size > 0) {
            console.log(`📎 Found ${message.attachments.size} attachment(s). Building embed with code block...`);

            // Map each attachment to its URL and join with a newline for the list
            const linksList = message.attachments.map(attachment => attachment.url).join('\n');

            const linkEmbed = new EmbedBuilder()
                .setColor(0x0099FF)
                .setTitle('🔗 Direct File Link(s)')
                .setDescription(
                    // MODIFIED: Wrap the list of links in a multi-line code block.
                    // The ``` at the start and end tells Discord to display this as raw text.
                    '```' + linksList + '```'
                )
                .setTimestamp()
                .setFooter({ text: 'Generated by Dumb Bot' });


            message.reply({
                embeds: [linkEmbed],
                allowedMentions: { repliedUser: false }
            }).catch(console.error);
        }
    }
});


// 4. LOGIN
// ===================================
// (This section remains unchanged)
client.login(process.env.DISCORD_TOKEN);